rules:
  color-hex-case: "lower"
  color-hex-length: "short"
  color-named: "always-where-possible"
  color-no-invalid-hex: true
  font-family-name-quotes: "always-where-recommended"
  font-weight-notation: "named-where-possible"
  function-comma-space-after: "always-single-line"
  function-comma-space-before: "never"
  function-linear-gradient-no-nonstandard-direction: true
  function-name-case: "lower"
  function-parentheses-space-inside: "never"
  function-url-quotes: "always"
  function-whitespace-after: "always"
  number-leading-zero: "never"
  number-no-trailing-zeros: true
  string-no-newline: true
  string-quotes: "double"
  length-zero-no-unit: true
  unit-case: "lower"
  unit-no-unknown: true
  value-keyword-case: "lower"
  value-list-comma-newline-before: "never-multi-line"
  value-list-comma-space-after: "always-single-line"
  value-list-comma-space-before: "never"
  shorthand-property-no-redundant-values: true
  property-case: "lower"
  property-no-unknown: true
  keyframe-declaration-no-important: true
  declaration-bang-space-after: "never"
  declaration-bang-space-before: "always"
  declaration-colon-space-after: "always"
  declaration-colon-space-before: "never"
  declaration-block-no-duplicate-properties: true
  declaration-block-no-ignored-properties: true
  declaration-block-no-shorthand-property-overrides: true
  declaration-block-semicolon-newline-before: "never-multi-line"
  declaration-block-trailing-semicolon: "always"
  block-closing-brace-empty-line-before: "never"
  block-closing-brace-newline-after: "always-multi-line"
  block-closing-brace-newline-before: "always-multi-line"
  block-no-empty: true
  block-opening-brace-newline-after: "always-multi-line"
  selector-attribute-brackets-space-inside: "never"
  selector-attribute-operator-space-after: "never"
  selector-attribute-operator-space-before: "never"
  selector-combinator-space-after: "always"
  selector-combinator-space-before: "always"
  selector-no-qualifying-type:
    - true
    - ignore:
      - "attribute"
      - "class"
  selector-pseudo-class-case: "lower"
  selector-pseudo-class-no-unknown: true
  selector-pseudo-class-parentheses-space-inside: "never"
  selector-pseudo-element-case: "lower"
  selector-pseudo-element-colon-notation: "double"
  selector-pseudo-element-no-unknown: true
  selector-type-case: "lower"
  selector-type-no-unknown: true
  selector-list-comma-space-after: "always"
  selector-list-comma-space-before: "never"
  media-feature-colon-space-after: "always"
  media-feature-colon-space-before: "never"
  media-feature-name-case: "lower"
  media-feature-no-missing-punctuation: true
  media-feature-parentheses-space-inside: "never"
  media-feature-range-operator-space-after: "always"
  media-feature-range-operator-space-before: "always"
  media-query-list-comma-space-after: "always"
  media-query-list-comma-space-before: "never"
  at-rule-name-case: "lower"
  at-rule-no-unknown: true
  comment-no-empty: true
  comment-whitespace-inside: "always"
  indentation: "tab"
  no-browser-hacks: true
  no-duplicate-selectors: true
  no-empty-source: true
  no-eol-whitespace: true
  no-extra-semicolons: true
  no-invalid-double-slash-comments: true
  no-missing-end-of-source-newline: true
  no-unknown-animations: true
